name: Reusable workflow
on: 
  workflow_call:
    inputs:
      who-to-greet:
        default: 'World'
        required: true
        type: string
    outputs:
      current-time:
        description: The time 
        value: ${{jobs.reusable-job.outputs.current-time}}

jobs:
   reusable-job:
      runs-on: ubuntu-latest
      outputs:
        current-tim: ${{steps.time.outputs.time}}

      steps:
        - name: Hello
          run: echo Hello 

        - name: Get Time
          id: time
          run: echo "time=$(date)" >> $GITHUB_OUTPUT